import jsPDF from 'jspdf';
import { renderCardSide } from './cardRenderer';

interface PdfOptions {
    watermarkUrl?: string; // URL to watermark image
}

export const generateBatchProofPDF = async (
    students: any[],
    template: any,
    options: PdfOptions = {}
) => {
    // A4 Dimensions in mm
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = 210;
    const pageHeight = 297;
    const margin = 10;

    // Card Dimensions (Standard ID card is 85.6mm x 54mm)
    // We'll scale slightly to fit checks 3x3 nicely or 2x4?
    // 85.6 * 2 = 171 (fits in 210 width with margin)
    // 54 * 4 = 216 (fits in 297 height)
    // Let's do 2 columns, 4 rows = 8 cards per page.

    const cardWidth = 85.6;
    const cardHeight = 54;
    const gapX = 10;
    const gapY = 10;

    const cols = 2;
    const rows = 4;
    const cardsPerPage = cols * rows;

    let currentCardIndex = 0;

    // Load watermark image
    let watermarkImg: HTMLImageElement | null = null;
    if (options.watermarkUrl) {
        try {
            watermarkImg = await new Promise((resolve) => {
                const img = new Image();
                img.crossOrigin = 'anonymous';
                img.onload = () => resolve(img);
                img.onerror = () => resolve(null); // Continue without if fails
                img.src = options.watermarkUrl!;
            });
        } catch (e) {
            console.warn("Failed to load watermark", e);
        }
    }

    // Helper to add watermark to current page
    const addWatermark = () => {
        if (!watermarkImg) return;

        // Save current state (manually reset later)

        // Set Transparency
        pdf.setGState(new (pdf as any).GState({ opacity: 0.15 })); // Light watermark

        // Tile the watermark
        const wmWidth = 60; // Size of watermark
        const aspect = (watermarkImg!.width || 1) / (watermarkImg!.height || 1);
        const drawH = wmWidth / aspect;

        const xCount = Math.ceil(pageWidth / 80);
        const yCount = Math.ceil(pageHeight / 80);

        for (let i = 0; i < xCount; i++) {
            for (let j = 0; j < yCount; j++) {
                const x = i * 80 + 20;
                const y = j * 80 + 40;

                // Add Image with Rotation (45 degrees)
                pdf.addImage(watermarkImg!, 'PNG', x, y, wmWidth, drawH, undefined, 'FAST', 45);
            }
        }

        // Restore Opacity to 1.0 for next operations (or next page)
        pdf.setGState(new (pdf as any).GState({ opacity: 1.0 }));
    };

    while (currentCardIndex < students.length) {
        if (currentCardIndex > 0) pdf.addPage();

        // --- 1. Draw Cards First (Bottom Layer) ---
        for (let i = 0; i < cardsPerPage; i++) {
            if (currentCardIndex >= students.length) break;

            const student = students[currentCardIndex];

            // Render Front Side 
            const design = template.front_design?.front_design || template.front_design;

            // Render high quality for PDF
            const renderWidth = 1011;
            const renderHeight = 638;

            try {
                const dataUrl = await renderCardSide(design, student, renderWidth, renderHeight);

                if (dataUrl) {
                    const col = i % cols;
                    const row = Math.floor(i / cols);

                    const x = margin + (col * (cardWidth + gapX));
                    const y = margin + (row * (cardHeight + gapY));

                    // Add Card Image
                    pdf.addImage(dataUrl, 'PNG', x, y, cardWidth, cardHeight);

                    // Draw Border around card
                    pdf.setDrawColor(200, 200, 200); // Light Gray
                    pdf.rect(x, y, cardWidth, cardHeight);
                }
            } catch (e) {
                console.error("Error rendering card for PDF", e);
            }

            currentCardIndex++;
        }

        // --- 2. Draw Watermark Second (Top Layer / Overlay) ---
        // This ensures the watermark is drawn ON TOP of the cards
        addWatermark();

        // --- 3. Add Footer ---
        pdf.setFontSize(8);
        pdf.setTextColor(150);
        pdf.text("Draft Proof - Not for Official Use - Generated by ID Perfect", pageWidth / 2, pageHeight - 5, { align: 'center' });
    }

    return pdf;
};
